.TH  userman 1 userman\-0.1
.SH NAME 
userman \- simple program to manage users
.SH SYNOPSIS
.B userman
.RB [ \-test ]
.SH DESCRIPTION
userman is high level shell program for manupiulating users administrators should usually use userman
.SH OPTIONS
The userman does not take any options. However, you can supply username.
.SH SEE ALSO
useradd(8), passwd(5)
.SH BUGS
No known bugs.
.SH AUTHOR
a-amr (sseadaamr@gmail.com)
